name = "blah"
version = "1.0.0"

description = "fake data generation for gleam"
licences = ["Apache-2.0"]
links = [
  {title = "Gleam", href = "https://gleam.run"},
]
repository = {type = "github", user = "massivefermion", repo = "blah"}

gleam = ">= 0.33.0"
internal_modules = [
  "blah/en/*",
  "blah/utils",
  "blah/locales/*",
]

[dependencies]
birl = "~> 1.1"
gleam_stdlib = "~> 0.34"

[dev-dependencies]
gleeunit = "~> 1.0"
